### ISSUE TITLE
sorry im dumb

### ISSUE THREAD

**Issue by Sagem0** [Miloet/LC_Map#3]
sorry im dumb

**Comment by Miloet** [comment]
Hi! I would still like to know what caused it. Was it an older version of the mod?

**Comment by Sagem0** [comment]
Hey sorry
I did the bug report on the wrong mod page.

The lag spikes are caused by the portable terminal from Advanced Company, but i was your handhelp map* in my head xD

I'm sorry !!

**Comment by Miloet** [comment]
No need to be sorry! I hope the mod creator can fix it soon!!
