### ISSUE TITLE
See other players perspective

### ISSUE THREAD

**Issue by PseudoCoffee** [Miloet/LC_Map#4]
Would it be possible to add a button to switch camera to see the perspective of other players?

**Comment by Miloet** [comment]
It is possible and relatively easy. However, I don't know if it fits in with the mod's intentions. It's meant to be distinct from the ship monitor, not a copy of it. I believe that lethal things has a map that more closely resembles the ship monitor (without some of my mods customization, however...)

**Comment by PseudoCoffee** [comment]
That mod adds many undesired features so I prefer to stick to small mods that add a single feature.
