### ISSUE TITLE
[Bug] Picking up the handheld map causes flicker

### ISSUE THREAD

**Issue by JohnMetroid** [Miloet/LC_Map#5]
Hey there,

The handheld map is amazing, but we're getting a bug where picking up the map will cause a flicker.  I'm not sure if it's a mod incompatibility or if it's isolated to Handheld Map itself.  The log doesn't throw any error when it flickers, so I don't have any insight on that front.  But I've taken a gif of the flickering and attached a mod profile code, if that helps.

It *seems* like the first time it's picked up in orbit or on any given moon, this doesn't occur.  But subsequently dropping and picking up the handheld map will flicker every time (at least as far as I can tell from brief testing)

Profile: 01911c84-266a-5260-af6e-e7a2bc163a13
gif: https://i.imgur.com/d5VHHk0.gif

Thanks

**Comment by Miloet** [comment]
Hello! Apologies, this has been a know bug for a long time but during the
most active part of development it was quite low priority and kinda slipped
through. Ill look into it and it should be fixed within 24 hours. Thank you
for your report.

**Comment by Miloet** [comment]
The issue should be fixed now

**Comment by JohnMetroid** [comment]
Thanks so much for the bugfix.  And for doing it so quickly.

Cheers
